// import "../../globals.css";
import CliSideNav from "@/components/CliSideNav";
import Description from "@/components/Description";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <div className="w-[300px]  h-screen p-4 border-r-2 ">
            <div className="text-lg font-semibold text-center py-4">
              Glim Cli
            </div>
            <CliSideNav />
          </div>
          <div className="w-full overflow-auto">
            <div className="mx-auto max-w-screen-xl px-4 pb-8 pt-16 sm:px-6 lg:px-8 lg:pt-24  ">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
